begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(12);
select ok((select relrowsecurity from pg_class where oid='public.logistics_operations'::regclass),'Operations enforce RLS');
select ok((select relrowsecurity from pg_class where oid='public.logistics_operation_history'::regclass),'History enforces RLS');
select ok(not has_table_privilege('anon','public.logistics_operations','SELECT'),'Anonymous users cannot read costs');
select ok(not has_table_privilege('authenticated','public.logistics_operations','INSERT'),'Writes go through RPC');
select ok(not has_table_privilege('authenticated','public.logistics_operation_history','INSERT'),'History cannot be forged');
select ok(not has_table_privilege('authenticated','public.logistics_operation_history','DELETE'),'History cannot be deleted by clients');
select ok(not has_function_privilege('anon','public.list_logistics_operations()','EXECUTE'),'Anonymous list denied');
select ok(not has_function_privilege('anon','public.save_logistics_operation(jsonb,timestamptz)','EXECUTE'),'Anonymous save denied');
select ok(not has_function_privilege('authenticated','public.capture_logistics_operation_history()','EXECUTE'),'Audit function cannot be invoked directly');
select set_config('request.jwt.claim.sub','',true);
select throws_ok($$select public.list_logistics_operations()$$,'42501','No tienes permiso para consultar logística.','Missing identity cannot list');
select throws_ok($$select public.save_logistics_operation('{}'::jsonb,null)$$,'42501','Solo gestión puede modificar este servicio.','Missing identity cannot save');
select throws_ok($$select public.list_logistics_operation_history('material','00000000-0000-0000-0000-000000000001')$$,'42501','No tienes permiso para consultar el historial.','Missing identity cannot view history');
select * from finish();
rollback;
