import type { AppRoute } from "@/routes/app-route-types";
import {
  ConsumosTool,
  Disponibilidad,
  Feedback,
  FestivalArtistManagement,
  FestivalGearManagement,
  FestivalManagement,
  LightsConsumosTool,
  LightsMemoriaTecnica,
  LightsPesosTool,
  ModernHojaDeRuta,
  PesosTool,
  RackBuilderConnectorManagerPage,
  RackBuilderDeviceManagerPage,
  RackBuilderLayoutEditorPage,
  RackBuilderLayoutPrintPage,
  RackBuilderPanelLayoutEditorPage,
  RackBuilderPanelLayoutManagerPage,
  RackBuilderPanelLayoutPrintPage,
  RackBuilderPanelLayoutsOverviewPage,
  RackBuilderProjectManagerPage,
  RackBuilderProjectPrintPage,
  RackBuilderRackManagerPage,
  SoundVisionFiles,
  StagePlot,
  SysCalc,
  TourManagementWrapper,
  UserManual,
  VideoConsumosTool,
  VideoMemoriaTecnica,
  VideoPesosTool,
} from "@/routes/app-route-pages";

export const secondaryAppRoutes: readonly AppRoute[] = [
  {
    id: "feedback",
    path: "/feedback",
    component: Feedback,
    layout: "app",
    access: "authenticated",
    breadcrumb: { label: "Comentarios y soporte" },
  },
  {
    id: "soundVisionFiles",
    path: "/soundvision-files",
    component: SoundVisionFiles,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Archivos de SoundVision" },
  },
  {
    id: "manual",
    path: "/manual",
    component: UserManual,
    layout: "app",
    access: "authenticated",
    breadcrumb: { label: "Manual" },
  },
  {
    id: "tourManagement",
    path: "/tour-management/:tourId",
    component: TourManagementWrapper,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "tourManagement",
    subscriptionRouteKey: "/tour-management",
    breadcrumb: { label: "Gestión de gira", parentPath: "/tours" },
  },
  {
    id: "soundPesos",
    path: "/sound/pesos",
    component: PesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/sound",
    chrome: { mobileFullscreen: true },
    breadcrumb: { label: "Pesos", parentPath: "/sound" },
  },
  {
    id: "soundConsumos",
    path: "/sound/consumos",
    component: ConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/sound",
    chrome: { mobileFullscreen: true },
    breadcrumb: { label: "Consumos", parentPath: "/sound" },
  },
  {
    id: "pesosTool",
    path: "/pesos-tool",
    component: PesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "pesosTool",
    breadcrumb: { label: "Pesos" },
  },
  {
    id: "lightsPesosTool",
    path: "/lights-pesos-tool",
    component: LightsPesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/lights",
    breadcrumb: { label: "Pesos luces" },
  },
  {
    id: "videoPesosTool",
    path: "/video-pesos-tool",
    component: VideoPesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/video",
    breadcrumb: { label: "Pesos vídeo" },
  },
  {
    id: "consumosTool",
    path: "/consumos-tool",
    component: ConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "consumosTool",
    breadcrumb: { label: "Consumos" },
  },
  {
    id: "lightsConsumosTool",
    path: "/lights-consumos-tool",
    component: LightsConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/lights",
    breadcrumb: { label: "Consumos luces" },
  },
  {
    id: "stagePlot",
    path: "/stage-plot",
    component: StagePlot,
    layout: "app",
    access: "soundTools",
    breadcrumb: { label: "Plano de escenario" },
  },
  {
    id: "sysCalc",
    path: "/syscalc",
    component: SysCalc,
    layout: "app",
    access: "soundToolsWithTechnician",
    breadcrumb: { label: "SysCalc" },
  },
  {
    id: "rackBuilderProjects",
    path: "/rack-builder",
    component: RackBuilderProjectManagerPage,
    layout: "app",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder" },
  },
  {
    id: "rackBuilderProjectsAlias",
    path: "/rack-builder/projects",
    component: RackBuilderProjectManagerPage,
    layout: "app",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder" },
  },
  {
    id: "rackBuilderRacks",
    path: "/rack-builder/racks",
    component: RackBuilderRackManagerPage,
    layout: "app",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Bastidores" },
  },
  {
    id: "rackBuilderDevices",
    path: "/rack-builder/devices",
    component: RackBuilderDeviceManagerPage,
    layout: "app",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Dispositivos" },
  },
  {
    id: "rackBuilderConnectors",
    path: "/rack-builder/connectors",
    component: RackBuilderConnectorManagerPage,
    layout: "app",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Conectores" },
  },
  {
    id: "rackBuilderPanelsOverview",
    path: "/rack-builder/panels",
    component: RackBuilderPanelLayoutsOverviewPage,
    layout: "app",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Diseños de panel" },
  },
  {
    id: "rackBuilderLayoutEditor",
    path: "/rack-builder/editor/project/:projectId",
    component: RackBuilderLayoutEditorPage,
    layout: "fullscreen",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Editor" },
  },
  {
    id: "rackBuilderPanelManager",
    path: "/rack-builder/editor/project/:projectId/panels",
    component: RackBuilderPanelLayoutManagerPage,
    layout: "app",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Diseños de panel" },
  },
  {
    id: "rackBuilderPanelEditor",
    path: "/rack-builder/editor/project/:projectId/panels/:panelLayoutId",
    component: RackBuilderPanelLayoutEditorPage,
    layout: "fullscreen",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Editor de panel" },
  },
  {
    id: "rackBuilderPanelPrint",
    path: "/rack-builder/editor/project/:projectId/panels/:panelLayoutId/print",
    component: RackBuilderPanelLayoutPrintPage,
    layout: "fullscreen",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Impresión de panel" },
  },
  {
    id: "rackBuilderProjectPrintAll",
    path: "/rack-builder/editor/project/:projectId/print/all",
    component: RackBuilderProjectPrintPage,
    layout: "fullscreen",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Impresión de proyecto" },
  },
  {
    id: "rackBuilderLayoutPrint",
    path: "/rack-builder/editor/project/:projectId/print/:layoutId",
    component: RackBuilderLayoutPrintPage,
    layout: "fullscreen",
    access: "rackBuilder",
    breadcrumb: { label: "Rack Builder – Impresión de diseño" },
  },
  {
    id: "videoConsumosTool",
    path: "/video-consumos-tool",
    component: VideoConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/video",
    breadcrumb: { label: "Consumos vídeo" },
  },
  {
    id: "lightsMemoriaTecnica",
    path: "/lights-memoria-tecnica",
    component: LightsMemoriaTecnica,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Memoria técnica luces" },
  },
  {
    id: "videoMemoriaTecnica",
    path: "/video-memoria-tecnica",
    component: VideoMemoriaTecnica,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Memoria técnica vídeo" },
  },
  {
    id: "hojaDeRuta",
    path: "/hoja-de-ruta",
    component: ModernHojaDeRuta,
    layout: "app",
    access: "management",
    subscriptions: "hojaDeRuta",
    breadcrumb: { label: "Hoja de ruta" },
    nav: {
      id: "hoja-de-ruta",
      label: "Hoja de Ruta",
      shortcut: { id: "nav-hoja-de-ruta", keybind: "Ctrl+Shift+H", icon: "Map" },
    },
  },
  {
    id: "tourSoundPesos",
    path: "/tours/:tourId/sound/pesos",
    component: PesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "tours",
    subscriptionRouteKey: "/tours",
    breadcrumb: { label: "Pesos", parentPath: "/tour-management/:tourId" },
  },
  {
    id: "tourSoundConsumos",
    path: "/tours/:tourId/sound/consumos",
    component: ConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "tours",
    subscriptionRouteKey: "/tours",
    breadcrumb: { label: "Consumos", parentPath: "/tour-management/:tourId" },
  },
  {
    id: "tourLightsPesos",
    path: "/tours/:tourId/lights/pesos",
    component: LightsPesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "tours",
    subscriptionRouteKey: "/tours",
    breadcrumb: { label: "Pesos luces", parentPath: "/tour-management/:tourId" },
  },
  {
    id: "tourLightsConsumos",
    path: "/tours/:tourId/lights/consumos",
    component: LightsConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "tours",
    subscriptionRouteKey: "/tours",
    breadcrumb: { label: "Consumos luces", parentPath: "/tour-management/:tourId" },
  },
  {
    id: "tourVideoPesos",
    path: "/tours/:tourId/video/pesos",
    component: VideoPesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "tours",
    subscriptionRouteKey: "/tours",
    breadcrumb: { label: "Pesos vídeo", parentPath: "/tour-management/:tourId" },
  },
  {
    id: "tourVideoConsumos",
    path: "/tours/:tourId/video/consumos",
    component: VideoConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "tours",
    subscriptionRouteKey: "/tours",
    breadcrumb: { label: "Consumos vídeo", parentPath: "/tour-management/:tourId" },
  },
  {
    id: "tourDateSoundPesos",
    path: "/tour-dates/:tourDateId/sound/pesos",
    component: PesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Pesos" },
  },
  {
    id: "tourDateSoundConsumos",
    path: "/tour-dates/:tourDateId/sound/consumos",
    component: ConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Consumos" },
  },
  {
    id: "tourDateLightsPesos",
    path: "/tour-dates/:tourDateId/lights/pesos",
    component: LightsPesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Pesos luces" },
  },
  {
    id: "tourDateLightsConsumos",
    path: "/tour-dates/:tourDateId/lights/consumos",
    component: LightsConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Consumos luces" },
  },
  {
    id: "tourDateVideoPesos",
    path: "/tour-dates/:tourDateId/video/pesos",
    component: VideoPesosTool,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Pesos vídeo" },
  },
  {
    id: "tourDateVideoConsumos",
    path: "/tour-dates/:tourDateId/video/consumos",
    component: VideoConsumosTool,
    layout: "app",
    access: "managementAndHouseTech",
    breadcrumb: { label: "Consumos vídeo" },
  },
  {
    id: "disponibilidad",
    path: "/disponibilidad",
    component: Disponibilidad,
    layout: "app",
    access: "disponibilidad",
    breadcrumb: { label: "Disponibilidad" },
  },
  {
    id: "festivalManagement",
    path: "/festival-management/:jobId",
    component: FestivalManagement,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "festivalManagement",
    subscriptionRouteKey: "/festival-management",
    breadcrumb: { label: "Festival", parentPath: "/festivals" },
  },
  {
    id: "festivalManagementArtists",
    path: "/festival-management/:jobId/artists",
    component: FestivalArtistManagement,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "festivalManagementArtists",
    subscriptionRouteKey: "/festival-management/artists",
    breadcrumb: { label: "Artistas", parentPath: "/festival-management/:jobId" },
  },
  {
    id: "festivalManagementGear",
    path: "/festival-management/:jobId/gear",
    component: FestivalGearManagement,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "festivalManagementGear",
    subscriptionRouteKey: "/festival-management/gear",
    breadcrumb: { label: "Equipamiento", parentPath: "/festival-management/:jobId" },
  },
  {
    id: "festivalManagementScheduling",
    path: "/festival-management/:jobId/scheduling",
    component: FestivalManagement,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "festivalManagementScheduling",
    subscriptionRouteKey: "/festival-management/scheduling",
    breadcrumb: { label: "Programación", parentPath: "/festival-management/:jobId" },
  },
];
