import type { AppRoute } from "@/routes/app-route-types";
import {
  Achievements,
  ActivityCenter,
  Announcements,
  ArtistRequirementsForm,
  ArtistRequirementsFormBlank,
  Auth,
  Dashboard,
  EquipmentManagement,
  ExpensesPage,
  Festivals,
  FormSubmitted,
  GlobalTasks,
  IncidentReports,
  JobAssignmentMatrix,
  Lights,
  Logistics,
  MorningSummary,
  PayoutsDueFortnights,
  Personal,
  Privacy,
  Profile,
  ProjectManagement,
  RatesCenterPage,
  Settings,
  Sound,
  TechnicianDashboard,
  TechnicianSuperApp,
  TechnicianUnavailability,
  Timesheets,
  TourShare,
  Tours,
  Video,
  Wallboard,
  WallboardPresets,
  WallboardPublic,
} from "@/routes/app-route-pages";

export const primaryAppRoutes: readonly AppRoute[] = [
  {
    id: "auth.root",
    path: "/",
    component: Auth,
    layout: "public",
    access: "public",
  },
  {
    id: "auth",
    path: "/auth",
    component: Auth,
    layout: "public",
    access: "public",
  },
  {
    id: "wallboard.public",
    path: "/wallboard/public/:token/:presetSlug?",
    component: WallboardPublic,
    layout: "public",
    access: "public",
  },
  {
    id: "tourShare",
    path: "/tour-share/:token",
    component: TourShare,
    layout: "public",
    access: "public",
  },
  {
    id: "privacy",
    path: "/privacy",
    component: Privacy,
    layout: "public",
    access: "public",
    breadcrumb: { label: "Privacidad" },
  },
  {
    id: "festival.artistForm.blank",
    path: "/festival/artist-form/blank",
    component: ArtistRequirementsFormBlank,
    layout: "public",
    access: "public",
  },
  {
    id: "festival.artistForm",
    path: "/festival/artist-form/:token",
    component: ArtistRequirementsForm,
    layout: "public",
    access: "public",
  },
  {
    id: "festival.formSubmitted",
    path: "/festival/form-submitted",
    component: FormSubmitted,
    layout: "public",
    access: "public",
  },
  {
    id: "wallboard",
    path: "/wallboard/:presetSlug?",
    component: Wallboard,
    layout: "fullscreen",
    access: "authenticated",
    chrome: { suppress: true },
    breadcrumb: { label: "Wallboard" },
  },
  {
    id: "techApp",
    path: "/tech-app",
    component: TechnicianSuperApp,
    layout: "fullscreen",
    access: "technicianApp",
    breadcrumb: { label: "App técnico" },
    nav: {
      id: "tech-app",
      label: "Panel técnico",
      mobileLabel: "Panel",
      shortcut: { id: "nav-tech-app", icon: "Smartphone" },
    },
  },
  {
    id: "achievements",
    path: "/achievements",
    component: Achievements,
    layout: "fullscreen",
    access: "authenticated",
    breadcrumb: { label: "Logros" },
  },
  {
    id: "sound",
    path: "/sound",
    component: Sound,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/sound",
    chrome: { mobileFullscreen: true },
    breadcrumb: { label: "Sonido" },
    nav: {
      id: "admin-sound",
      label: "Sonido",
      mobileLabel: "Sonido",
      shortcut: { id: "nav-sound", keybind: "Ctrl+2", icon: "Volume2" },
    },
  },
  {
    id: "personal",
    path: "/personal",
    component: Personal,
    layout: "app",
    access: "personal",
    breadcrumb: { label: "Agenda personal" },
    nav: {
      id: "personal",
      label: "Agenda personal",
      mobileLabel: "Agenda",
      shortcut: { id: "nav-personal", keybind: "Ctrl+8", icon: "Users" },
    },
  },
  {
    id: "dashboard",
    path: "/dashboard",
    component: Dashboard,
    layout: "app",
    access: "dashboard",
    subscriptions: "dashboard",
    breadcrumb: { label: "Panel principal" },
    nav: {
      id: "management-dashboard",
      label: "Panel principal",
      mobileLabel: "Panel",
      shortcut: { id: "nav-dashboard", keybind: "Ctrl+1", icon: "LayoutDashboard" },
    },
  },
  {
    id: "technicianDashboard",
    path: "/technician-dashboard",
    component: TechnicianDashboard,
    layout: "app",
    access: "technicianDashboard",
    subscriptions: "technicianDashboard",
    breadcrumb: { label: "Panel técnico" },
    nav: {
      id: "technician-dashboard",
      label: "Panel técnico",
      mobileLabel: "Panel",
      shortcut: { id: "nav-technician-dashboard", keybind: "Ctrl+Shift+1", icon: "Wrench" },
    },
  },
  {
    id: "technicianUnavailability",
    path: "/dashboard/unavailability",
    component: TechnicianUnavailability,
    layout: "app",
    access: "technicianUnavailability",
    breadcrumb: { label: "Mi disponibilidad", parentPath: "/technician-dashboard" },
  },
  {
    id: "morningSummary",
    path: "/morning-summary",
    component: MorningSummary,
    layout: "app",
    access: "authenticated",
    breadcrumb: { label: "Resumen de mañana" },
  },
  {
    id: "lights",
    path: "/lights",
    component: Lights,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/lights",
    breadcrumb: { label: "Luces" },
    nav: {
      id: "admin-lights",
      label: "Luces",
      mobileLabel: "Luces",
      shortcut: { id: "nav-lights", keybind: "Ctrl+3", icon: "Lightbulb" },
    },
  },
  {
    id: "video",
    path: "/video",
    component: Video,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "department",
    subscriptionRouteKey: "/video",
    breadcrumb: { label: "Vídeo" },
    nav: {
      id: "admin-video",
      label: "Vídeo",
      mobileLabel: "Vídeo",
      shortcut: { id: "nav-video", keybind: "Ctrl+4", icon: "Video" },
    },
  },
  {
    id: "logistics",
    path: "/logistics",
    component: Logistics,
    layout: "app",
    access: "projectAndHouseTech",
    subscriptions: "logistics",
    breadcrumb: { label: "Logística" },
    nav: {
      id: "logistics",
      label: "Logística",
      mobileLabel: "Logística",
      shortcut: { id: "nav-logistics", keybind: "Ctrl+5", icon: "Truck" },
    },
  },
  {
    id: "profile",
    path: "/profile",
    component: Profile,
    layout: "app",
    access: "authenticated",
    subscriptions: "profile",
    breadcrumb: { label: "Perfil" },
    nav: {
      id: "profile",
      label: "Perfil",
      mobileLabel: "Perfil",
      shortcut: { id: "nav-profile", keybind: "Ctrl+Shift+P", icon: "User" },
    },
  },
  {
    id: "settings",
    path: "/settings",
    component: Settings,
    layout: "app",
    access: "management",
    subscriptions: "settings",
    breadcrumb: { label: "Ajustes" },
    nav: {
      id: "settings",
      label: "Ajustes",
      mobileLabel: "Ajustes",
      shortcut: { id: "nav-settings", keybind: "Ctrl+,", icon: "Settings" },
    },
  },
  {
    id: "projectManagement",
    path: "/project-management",
    component: ProjectManagement,
    layout: "app",
    access: "projectOperations",
    subscriptions: "projectManagement",
    breadcrumb: { label: "Gestión de proyectos" },
    nav: {
      id: "project-management",
      label: "Gestión de proyectos",
      mobileLabel: "Proyectos",
      shortcut: { id: "nav-project-management", keybind: "Ctrl+9", icon: "FolderKanban" },
    },
  },
  {
    id: "tasks",
    path: "/tasks",
    component: GlobalTasks,
    layout: "app",
    access: "tasks",
    breadcrumb: { label: "Tareas" },
  },
  {
    id: "equipmentManagement",
    path: "/equipment-management",
    component: EquipmentManagement,
    layout: "app",
    access: "authenticated",
    breadcrumb: { label: "Equipamiento" },
  },
  {
    id: "jobAssignmentMatrix",
    path: "/job-assignment-matrix",
    component: JobAssignmentMatrix,
    layout: "app",
    access: "management",
    breadcrumb: { label: "Matriz de asignaciones" },
    nav: {
      id: "job-assignment-matrix",
      label: "Matriz de asignaciones",
      mobileLabel: "Matriz",
      shortcut: { id: "nav-job-assignment-matrix", keybind: "Ctrl+0", icon: "Calendar" },
    },
  },
  {
    id: "activity",
    path: "/activity",
    component: ActivityCenter,
    layout: "app",
    access: "adminOnly",
    breadcrumb: { label: "Actividad" },
  },
  {
    id: "timesheets",
    path: "/timesheets",
    component: Timesheets,
    layout: "app",
    access: "authenticated",
    breadcrumb: { label: "Hojas de tiempo" },
    nav: {
      id: "timesheets",
      label: "Hojas de Tiempo",
      shortcut: { id: "nav-timesheets", keybind: "Ctrl+Shift+T", icon: "Clock" },
    },
  },
  {
    id: "tours",
    path: "/tours",
    component: Tours,
    layout: "app",
    access: "managementAndHouseTech",
    subscriptions: "tours",
    breadcrumb: { label: "Giras" },
    nav: {
      id: "tours",
      label: "Giras",
      mobileLabel: "Giras",
      shortcut: { id: "nav-tours", keybind: "Ctrl+6", icon: "Plane" },
    },
  },
  {
    id: "festivals",
    path: "/festivals",
    component: Festivals,
    layout: "app",
    access: "festivals",
    subscriptions: "festivals",
    breadcrumb: { label: "Festivales" },
    nav: {
      id: "festivals",
      label: "Festivales",
      mobileLabel: "Festivales",
      shortcut: { id: "nav-festivals", keybind: "Ctrl+7", icon: "Music" },
    },
  },
  {
    id: "incidentReports",
    path: "/incident-reports",
    component: IncidentReports,
    layout: "app",
    access: "management",
    breadcrumb: { label: "Partes de incidencias" },
  },
  {
    id: "announcements",
    path: "/announcements",
    component: Announcements,
    layout: "app",
    access: "adminOnly",
    breadcrumb: { label: "Anuncios" },
  },
  {
    id: "wallboardPresets",
    path: "/management/wallboard-presets",
    component: WallboardPresets,
    layout: "app",
    access: "adminOnly",
    breadcrumb: { label: "Wallboard" },
  },
  {
    id: "rates",
    path: "/management/rates",
    component: RatesCenterPage,
    layout: "app",
    access: "management",
    subscriptions: "rates",
    breadcrumb: { label: "Tarifas y extras" },
    nav: {
      id: "management-rates",
      label: "Tarifas y extras",
      mobileLabel: "Tarifas",
      shortcut: { id: "nav-rates", keybind: "Ctrl+Shift+R", icon: "DollarSign" },
    },
  },
  {
    id: "payoutsDue",
    path: "/management/payouts-due",
    component: PayoutsDueFortnights,
    layout: "app",
    access: "payoutsDue",
    breadcrumb: { label: "Pagos quincena" },
  },
  {
    id: "expenses",
    path: "/gastos",
    component: ExpensesPage,
    layout: "app",
    access: "projectOperations",
    subscriptions: "expenses",
    breadcrumb: { label: "Gastos" },
    nav: {
      id: "expenses",
      label: "Gastos",
      mobileLabel: "Gastos",
      shortcut: { id: "nav-expenses", keybind: "Ctrl+Shift+G", icon: "Receipt" },
    },
  },
];
