export interface ObliqueStrategy {
  english: string;
  spanish: string;
}

export const OBLIQUE_STRATEGIES: ObliqueStrategy[] = [
  { english: "Remove specifics and convert to ambiguities", spanish: "Elimina detalles específicos y conviértelos en ambigüedades" },
  { english: "Think of the radio", spanish: "Piensa en la radio" },
  { english: "Don’t be frightened of clichés", spanish: "No temas a los clichés" },
  { english: "What is the reality of the situation?", spanish: "¿Cuál es la realidad de la situación?" },
  { english: "Are there sections? Consider transitions", spanish: "¿Hay secciones? Considera las transiciones" },
  { english: "Turn it upside down", spanish: "Dale la vuelta" },
  { english: "Allow an easement (an easement is the abandonment of a stricture)", spanish: "Permite una servidumbre (una servidumbre es el abandono de una restricción)" },
  { english: "Simple subtraction", spanish: "Sustracción simple" },
  { english: "Remove specifics and convert to ambiguities", spanish: "Elimina detalles específicos y conviértelos en ambigüedades" },
  { english: "Go slowly all the way round the outside", spanish: "Ve despacio por todo el exterior" },
  { english: "A line has two sides", spanish: "Una línea tiene dos lados" },
  { english: "Infinitesimal gradations", spanish: "Gradaciones infinitesimales" },
  { english: "Make an exhaustive list of everything you might do and do the last thing on the list", spanish: "Haz una lista exhaustiva de todo lo que podrías hacer y haz lo último de la lista" },
  { english: "Into the impossible", spanish: "Hacia lo imposible" },
  { english: "Ask people to work against their better judgment", spanish: "Pide a la gente que actúe contra su mejor juicio" },
  { english: "Take away the elements in order of apparent non-importance", spanish: "Quita los elementos en orden de aparente poca importancia" },
  { english: "Change instrument roles", spanish: "Cambia los roles de los instrumentos" },
  { english: "Accretion", spanish: "Acreción" },
  { english: "Disconnect from desire", spanish: "Desconéctate del deseo" },
  { english: "Emphasize repetitions", spanish: "Enfatiza las repeticiones" },
  { english: "Don’t be afraid of things because they’re easy to do", spanish: "No temas a las cosas porque sean fáciles de hacer" },
  { english: "Is there something missing?", spanish: "¿Falta algo?" },
  { english: "Don’t be frightened to display your talents", spanish: "No temas mostrar tus talentos" },
  { english: "Breathe more deeply", spanish: "Respira más profundamente" },
  { english: "Honor thy error as a hidden intention", spanish: "Honra tu error como una intención oculta" },
  { english: "Only one element of each kind", spanish: "Solo un elemento de cada tipo" },
  { english: "Use unqualified people", spanish: "Usa gente no calificada" },
  { english: "How would you have done it?", spanish: "¿Cómo lo habrías hecho tú?" },
  { english: "Emphasize differences", spanish: "Enfatiza las diferencias" },
  { english: "Do nothing for as long as possible", spanish: "No hagas nada el mayor tiempo posible" },
  { english: "Bridges (build / burn)", spanish: "Puentes (construir / quemar)" },
  { english: "Water", spanish: "Agua" },
  { english: "You don’t have to be ashamed of using your own ideas", spanish: "No tienes que avergonzarte de usar tus propias ideas" },
  { english: "Tidy up", spanish: "Ordena" },
  { english: "Do the words need changing?", spanish: "¿Hay que cambiar las palabras?" },
  { english: "Ask your body", spanish: "Pregunta a tu cuerpo" },
  { english: "Make a sudden, destructive unpredictable action; incorporate", spanish: "Haz una acción repentina, destructiva e impredecible; incorpórala" },
  { english: "Consult other sources", spanish: "Consulta otras fuentes" },
  { english: "Use an unacceptable color", spanish: "Usa un color inaceptable" },
  { english: "Humanize something free of error", spanish: "Humaniza algo libre de errores" },
  { english: "Use filters", spanish: "Usa filtros" },
  { english: "Balance the consistency principle with the inconsistency principle", spanish: "Equilibra el principio de consistencia con el de inconsistencia" },
  { english: "Fill every beat with something", spanish: "Rellena cada pulso con algo" },
  { english: "Discard an axiom", spanish: "Descarta un axioma" },
  { english: "What wouldn’t you do?", spanish: "¿Qué no harías?" },
  { english: "Decorate, decorate", spanish: "Decora, decora" },
  { english: "Do nothing for as long as possible", spanish: "No hagas nada el mayor tiempo posible" },
  { english: "Listen to the quiet voice", spanish: "Escucha la voz tranquila" },
  { english: "Is it finished?", spanish: "¿Está terminado?" },
  { english: "Put in earplugs", spanish: "Ponte tapones en los oídos" },
  { english: "Give the game away", spanish: "Revela el secreto" },
  { english: "Reverse", spanish: "Invertir" },
  { english: "Abandon normal instruments", spanish: "Abandona los instrumentos normales" },
  { english: "Use fewer notes", spanish: "Usa menos notas" },
  { english: "Repetition is a form of change", spanish: "La repetición es una forma de cambio" },
  { english: "Give way to your worst impulse", spanish: "Cede a tu peor impulso" },
  { english: "Trust in the you of now", spanish: "Confía en tu yo de ahora" },
  { english: "What would your closest friend do?", spanish: "¿Qué haría tu amigo más cercano?" },
  { english: "Distorting time", spanish: "Distorsionando el tiempo" },
  { english: "Make a blank valuable by putting it in an exquisite frame", spanish: "Haz valioso un vacío poniéndolo en un marco exquisito" },
  { english: "The inconsistency principle", spanish: "El principio de inconsistencia" },
  { english: "Ghost echoes", spanish: "Ecos fantasma" },
  { english: "You can only make one dot at a time", spanish: "Solo puedes hacer un punto a la vez" },
  { english: "Just carry on", spanish: "Sigue adelante" },
  { english: "(Organic) machinery", spanish: "Maquinaria (orgánica)" },
  { english: "Don’t break the silence", spanish: "No rompas el silencio" },
  { english: "Discover the recipes you are using and abandon them", spanish: "Descubre las recetas que usas y abandónalas" },
  { english: "Cascades", spanish: "Cascadas" },
  { english: "Courage!", spanish: "¡Coraje!" },
  { english: "What mistakes did you make last time?", spanish: "¿Qué errores cometiste la última vez?" },
  { english: "You are an engineer", spanish: "Eres un ingeniero" },
  { english: "Consider different fading systems", spanish: "Considera diferentes sistemas de desvanecimiento" },
  { english: "Mute and continue", spanish: "Silencia y continúa" },
  { english: "It is quite possible (after all)", spanish: "Es bastante posible (después de todo)" },
  { english: "Don’t stress one thing more than another", spanish: "No estreses una cosa más que otra" },
  { english: "Remove ambiguities and convert to specifics", spanish: "Elimina ambigüedades y conviértelas en específicas" },
  { english: "Look at the order in which you do things", spanish: "Mira el orden en que haces las cosas" },
  { english: "Go outside. Shut the door.", spanish: "Sal afuera. Cierra la puerta." },
  { english: "Do we need holes?", spanish: "¿Necesitamos agujeros?" },
  { english: "Cluster analysis", spanish: "Análisis de conglomerados" },
  { english: "Work at a different speed", spanish: "Trabaja a una velocidad diferente" },
  { english: "Do something boring", spanish: "Haz algo aburrido" },
  { english: "Define an area as “safe” and use it as an anchor", spanish: "Define un área como “segura” y úsala como ancla" },
  { english: "Overtly resist change", spanish: "Resiste abiertamente el cambio" },
  { english: "Accept advice", spanish: "Acepta consejos" },
  { english: "Look closely at the most embarrassing details and amplify them", spanish: "Mira de cerca los detalles más vergonzosos y amplifícalos" },
  { english: "Mechanicalize something idiosyncratic", spanish: "Mecaniza algo idiosincrático" },
  { english: "Emphasize the flaws", spanish: "Enfatiza los defectos" },
  { english: "Remember those quiet evenings", spanish: "Recuerda aquellas noches tranquilas" },
  { english: "Take a break", spanish: "Tómate un descanso" },
  { english: "The tape is now the music", spanish: "La cinta ahora es la música" },
  { english: "Short circuit (example: a man eating peas with the idea that they will improve his virility shovels them straight into his lap)", spanish: "Cortocircuito (ejemplo: un hombre que come guisantes con la idea de que mejorarán su virilidad se los echa directamente en el regazo)" },
  { english: "Use an old idea", spanish: "Usa una idea antigua" },
  { english: "Destroy nothing / the most important thing", spanish: "Destruye nada / lo más importante" },
  { english: "Change nothing and continue with immaculate consistency", spanish: "No cambies nada y continúa con una consistencia inmaculada" },
  { english: "Imagine the music as a moving chain or caterpillar", spanish: "Imagina la música como una cadena o una oruga en movimiento" },
  { english: "Intentions (credibility of / nobility of / humility of)", spanish: "Intenciones (credibilidad / nobleza / humildad)" },
  { english: "Imagine the music as a set of disconnected events", spanish: "Imagina la música como un conjunto de eventos desconectados" },
  { english: "Imagine the piece as a set of disconnected events", spanish: "Imagina la pieza como un conjunto de eventos desconectados" },
  { english: "What are you really thinking about just now? Incorporate.", spanish: "¿En qué estás pensando realmente ahora? Incorpóralo." },
  { english: "Children’s voices (speaking / singing)", spanish: "Voces de niños (hablando / cantando)" },
  { english: "Assemble some of the instruments in a group and treat the group", spanish: "Reúne algunos instrumentos en un grupo y trata al grupo" },
  { english: "Shut the door and listen from outside", spanish: "Cierra la puerta y escucha desde fuera" },
  { english: "Is the tuning appropriate?", spanish: "¿Es adecuada la afinación?" },
  { english: "Look at a very small object, look at its centre", spanish: "Mira un objeto muy pequeño, mira su centro" },
  { english: "Feedback recordings into an acoustic situation", spanish: "Retroalimenta grabaciones en una situación acústica" },
  { english: "Towards the insignificant", spanish: "Hacia lo insignificante" },
  { english: "Simply a matter of work", spanish: "Simplemente una cuestión de trabajo" },
  { english: "Not building a wall but making a brick", spanish: "No construir un muro sino hacer un ladrillo" },
  { english: "Revaluation (a warm feeling)", spanish: "Revalorización (una sensación cálida)" },
  { english: "Disciplined self-indulgence", spanish: "Autoindulgencia disciplinada" },
  { english: "The most important thing is the thing most easily forgotten", spanish: "Lo más importante es lo más fácilmente olvidado" },
  { english: "Idiot glee", spanish: "Gozo idiota" },
  { english: "Be extravagant", spanish: "Sé extravagante" },
  { english: "State the problem in words as clearly as possible", spanish: "Expón el problema en palabras lo más claramente posible" },
  { english: "Always first steps", spanish: "Siempre los primeros pasos" },
  { english: "Question the heroic approach", spanish: "Cuestiona el enfoque heroico" },
  { english: "Always give yourself credit for having more than personality", spanish: "Siempre date crédito por tener más que personalidad" },
  { english: "Faced with a choice, do both", spanish: "Ante una elección, haz ambas" },
  { english: "Tape your mouth", spanish: "Cierra la boca con cinta" },
  { english: "Twist the spine", spanish: "Gira la columna" },
  { english: "Get your neck massaged", spanish: "Recibe un masaje en el cuello" },
  { english: "Do the washing up", spanish: "Lava los platos" },
  { english: "Convert a melodic element into a rhythmic element", spanish: "Convierte un elemento melódico en un elemento rítmico" },
  { english: "Spectrum analysis", spanish: "Análisis de espectro" },
  { english: "Lowest common denominator check (single beat / single note / single riff)", spanish: "Chequeo del mínimo común denominador (un solo pulso / una sola nota / un solo riff)" },
  { english: "Listen in total darkness, or in a very large room, very quietly", spanish: "Escucha en completa oscuridad, o en una habitación muy grande, muy silenciosamente" },
  { english: "Would anybody want it?", spanish: "¿Alguien lo querría?" },
  { english: "Retrace your steps", spanish: "Rehaz tus pasos" },
  { english: "Go to an extreme, move back to a more comfortable place", spanish: "Ve a un extremo, regresa a un lugar más cómodo" },
  { english: "Once the search is in progress, something will be found", spanish: "Una vez iniciada la búsqueda, se encontrará algo" },
  { english: "Only a part, not the whole", spanish: "Solo una parte, no el todo" },
  { english: "From nothing to more than nothing", spanish: "De nada a más que nada" },
  { english: "Be less critical more often", spanish: "Sé menos crítico más a menudo" },
];
