import {
  ENGLISH_POWER_TABLE_CONTROL_LABELS,
  SPANISH_POWER_TABLE_CONTROL_LABELS,
} from "@/features/technical-tools/power/PowerTableControls";
import type {
  ConsumosComponent,
  ConsumosDepartmentConfig,
  ConsumosLabels,
} from "./config";

const soundComponentDatabase: ConsumosComponent[] = [
  { id: 1, name: "LA12X", watts: 2000 },
  { id: 2, name: "LA8", watts: 1500 },
  { id: 3, name: "LA4X", watts: 750 },
  { id: 4, name: "PLM20000D", watts: 2900 },
  { id: 5, name: "Control FoH (L)", watts: 3500 },
  { id: 6, name: "Control FoH (S)", watts: 1500 },
  { id: 7, name: "Control Mon (L)", watts: 3500 },
  { id: 8, name: "Control Mon (S)", watts: 1500 },
  { id: 9, name: "RF Rack", watts: 2500 },
  { id: 10, name: "Backline", watts: 2500 },
  { id: 11, name: "Varios", watts: 1500 },
];

const videoComponentDatabase: ConsumosComponent[] = [
  { id: 1, name: "Pantalla Central", watts: 700 },
  { id: 2, name: "IMAGE Left", watts: 700 },
  { id: 3, name: "IMAGE Right", watts: 700 },
  { id: 4, name: "LED Screen", watts: 700 },
];

const lightComponentDatabase: ConsumosComponent[] = [
  { id: 1, name: "CAMEO OPUS S5", watts: 650, fixtureType: "led" },
  { id: 2, name: "CLAY PAKY A-LEDA K20", watts: 650, fixtureType: "led" },
  { id: 3, name: "CLAY PAKY A-LEDA K25", watts: 1100, fixtureType: "led" },
  { id: 4, name: "CLAY PAKY STORMY CC", watts: 800, fixtureType: "discharge" },
  { id: 5, name: "ELATION CHORUS LINE 16", watts: 750, fixtureType: "led" },
  { id: 6, name: "MARTIN MAC AURA", watts: 260, fixtureType: "led" },
  { id: 7, name: "MARTIN MAC VIPER", watts: 1200, fixtureType: "discharge" },
  { id: 8, name: "ROBE BMFL BLADE", watts: 2000, fixtureType: "discharge" },
  { id: 9, name: "ROBE BMFL SPOT", watts: 2000, fixtureType: "discharge" },
  { id: 10, name: "ROBE BMFL WASHBEAM", watts: 2000, fixtureType: "discharge" },
  { id: 11, name: "ROBE MEGAPOINTE", watts: 670, fixtureType: "discharge" },
  { id: 12, name: "ROBE POINTE", watts: 470, fixtureType: "discharge" },
  { id: 13, name: "TRITON BLUE 15R BEAM", watts: 500, fixtureType: "discharge" },
  { id: 14, name: "TRITON BLUE 15R SPOT", watts: 500, fixtureType: "discharge" },
  { id: 15, name: "TRITON BLUE WALLY 3715", watts: 650, fixtureType: "discharge" },
  { id: 16, name: "CAMEO AURO BAR 100", watts: 140, fixtureType: "led" },
  { id: 17, name: "ACL 250W (2 BARRAS)", watts: 2000, fixtureType: "incandescent" },
  { id: 18, name: "ACL 650W (2 BARRAS)", watts: 5200, fixtureType: "incandescent" },
  { id: 19, name: "BARRA PAR 64x6", watts: 6000, fixtureType: "incandescent" },
  { id: 20, name: "FRESNELL 2KW", watts: 2000, fixtureType: "incandescent" },
  { id: 21, name: "MOLEFAY BLINDER 4", watts: 2600, fixtureType: "incandescent" },
  { id: 22, name: "MOLEFAY BLINDER 8", watts: 5200, fixtureType: "incandescent" },
  { id: 23, name: "PAR 64", watts: 1000, fixtureType: "incandescent" },
  { id: 24, name: "ADMIRAL VINTAGE 53cm", watts: 60, fixtureType: "incandescent" },
  { id: 25, name: "ADMIRAL VINTAGE 38cm", watts: 60, fixtureType: "incandescent" },
  { id: 26, name: "FRESNELL 5KW", watts: 5000, fixtureType: "incandescent" },
  { id: 27, name: "MOLEFAY BLINDER 2", watts: 1300, fixtureType: "incandescent" },
  { id: 28, name: "RECORTE ETC 25º/50º", watts: 750, fixtureType: "incandescent" },
  { id: 29, name: "RECORTE ETC 15º/30º", watts: 750, fixtureType: "incandescent" },
  { id: 30, name: "RECORTE ETC 19º", watts: 750, fixtureType: "incandescent" },
  { id: 31, name: "RECORTE ETC 10º", watts: 750, fixtureType: "incandescent" },
  { id: 32, name: "RECORTE TB LED 25º/50º", watts: 300, fixtureType: "led" },
  { id: 33, name: "SUNSTRIP", watts: 500, fixtureType: "incandescent" },
  { id: 34, name: "CAMEO ZENIT 120", watts: 120, fixtureType: "led" },
  { id: 35, name: "ELATION SIXBAR 1000", watts: 150, fixtureType: "led" },
  { id: 36, name: "MARTIN ATOMIC 3000", watts: 3000, fixtureType: "discharge" },
  { id: 37, name: "SGM Q7", watts: 500, fixtureType: "led" },
  { id: 38, name: "ELATION SIXBAR 500", watts: 80, fixtureType: "led" },
  { id: 39, name: "SMOKE FACTORY TOUR HAZER II", watts: 1500, fixtureType: "smoke" },
  { id: 40, name: "ROBE 500 FT-PRO", watts: 1200, fixtureType: "smoke" },
  { id: 41, name: "SAHARA TURBO DRYER", watts: 1500, fixtureType: "smoke" },
  { id: 42, name: "ROBE SPIIDER", watts: 660, fixtureType: "led" },
  { id: 43, name: "GLP JDC1", watts: 1200, fixtureType: "led" },
  { id: 44, name: "CAMEO W3", watts: 325, fixtureType: "led" },
  { id: 45, name: "CHAUVET COLOR STRIKE M", watts: 750, fixtureType: "led" },
  { id: 46, name: "GLP X4 BAR 20", watts: 500, fixtureType: "led" },
  { id: 47, name: "ROBERT JULIAT ARAMIS", watts: 2500, fixtureType: "discharge" },
  { id: 48, name: "ROBERT JULIAT MERLIN", watts: 2500, fixtureType: "discharge" },
  { id: 49, name: "ROBERT JULIAT CYRANO", watts: 2500, fixtureType: "discharge" },
  { id: 50, name: "ROBERT JULIAT LANCELOT", watts: 4000, fixtureType: "discharge" },
  { id: 51, name: "ROBERT JULIAT KORRIGAN", watts: 1200, fixtureType: "discharge" },
  { id: 52, name: "PIXEL LINE IP", watts: 420, fixtureType: "led" },
  { id: 53, name: "COLORADO PXL BAR ", watts: 768, fixtureType: "led" },
  { id: 54, name: "AROLLA AQUA S-LT", watts: 600, fixtureType: "led" },
  { id: 55, name: "AROLLA AQUA HP", watts: 1900, fixtureType: "led" },
  { id: 56, name: "HY B-EYE K15 AQUA", watts: 680, fixtureType: "led" },
  { id: 57, name: "CLUSTER B2 FC", watts: 600, fixtureType: "led" },
  { id: 58, name: "ACME TORNADO", watts: 935, fixtureType: "led" },
  { id: 59, name: "CLAY PAKY A-LEDA K15", watts: 760, fixtureType: "led" },
  { id: 60, name: "AROLLA AQUA LT", watts: 1400, fixtureType: "led" },
  { id: 61, name: "CUARZO", watts: 400, fixtureType: "incandescent" },
  { id: 62, name: "MINI-B AQUA PX", watts: 375, fixtureType: "led" },
  { id: 63, name: "FREE PAR PRO 72", watts: 80, fixtureType: "led" },
  { id: 64, name: "FRESNEL 1 kW", watts: 1000, fixtureType: "incandescent" },
  { id: 65, name: "FRESNEL 300 W", watts: 300, fixtureType: "incandescent" },
  { id: 66, name: "ANTARI HZ 500", watts: 480, fixtureType: "smoke" },
  { id: 67, name: "TURBINA SHOWTEC SF-250", watts: 1035, fixtureType: "smoke" },
  { id: 68, name: "BRITEQ HZFOG II", watts: 1750, fixtureType: "smoke" },
  { id: 70, name: "GRAND MA3 FULL SIZE", watts: 450, fixtureType: "consoles" },
  { id: 71, name: "ULTIMO HYBRID", watts: 550, fixtureType: "discharge" },
];

const ENGLISH_LABELS: ConsumosLabels = {
  title: "Power Calculator",
  tourDefaultsBadge: "Tour Defaults Mode",
  tourDefaultsNoticeTitle: "Tour Defaults Mode Active",
  tourDefaultsNoticeBody:
    "Any tables you create will be saved as global defaults for this tour. These defaults will apply to all tour dates unless specifically overridden.",
  creatingDefaultsFor: "Creating defaults for:",
  overrideBadge: "Override Mode",
  overrideNoticeTitle: "Override Mode Active",
  overrideNoticeBody:
    "This job is part of a tour. Any tables you create will be saved as overrides for the specific tour date.",
  existingDefaultsHeading: "Existing Tour Defaults",
  readOnlyDefaultsHeading: "Tour Defaults (Read-Only)",
  existingOverridesHeading: "Existing Overrides",
  defaultBadge: "Default",
  savedBadge: "Saved",
  overrideTableBadge: "Override",
  edit: "Edit",
  deleteAction: "Delete",
  fohSchuko:
    "Se requiere potencia de 16A en formato schuko hembra en posicion FoH",
  supply: "Supply",
  supplyPlaceholder: "Select supply",
  singlePhase: "Monofásico (230 V)",
  threePhase: "Trifásico (400 V LL)",
  voltage: "Voltage",
  voltageHint: "230 V (1φ) o 400 V LL (3φ) por defecto en ES",
  powerFactor: "Power Factor (PF)",
  powerFactorHint:
    "Usa 0.9 si la PDU mezcla amplificadores nuevos y viejos (p.ej LA8).",
  safetyMargin: "Safety Margin",
  safetyMarginPlaceholder: "Select Safety Margin",
  selectJob: "Select Job",
  selectJobPlaceholder: "Select a job",
  stage: "Stage",
  tableName: "Table Name",
  defaultName: "Default Name",
  tableNamePlaceholder: "Enter table name",
  defaultNamePlaceholder: "Enter default name",
  editingTableSuffix: "(Editing Table)",
  editingOverrideSuffix: "(Editing Override)",
  position: "Position",
  noPosition: "No position",
  customOption: "Custom",
  customPosition: "Custom Position",
  customPositionPlaceholder: "Enter custom position",
  colQuantity: "Quantity",
  colLineName: "Name",
  lineNamePlaceholder: "Optional line name",
  colComponent: "Component",
  componentPlaceholder: "Select component",
  addComponent: "Add component",
  customComponentTitle: "New component",
  componentName: "Name",
  componentNamePlaceholder: "Enter component name",
  componentWatts: "Watts",
  componentType: "Fixture type",
  saveComponent: "Add component",
  cancel: "Cancel",
  colWatts: "Watts (per unit)",
  colPf: "PF (recommended by type)",
  colTotalWatts: "Total Watts",
  deleteRowAria: "Delete row",
  toastComponentSaved: "Component added to the catalog",
  toastComponentSaveError: "Failed to add the component",
  addRow: "Add Row",
  generateTable: "Generate Table",
  updateTable: "Update Table",
  createOverride: "Create Override",
  updateOverride: "Update Override",
  reset: "Reset",
  cancelEdit: "Cancel Edit",
  saveDefaultTables: "Save Default Tables",
  saveDefault: "Save",
  exportPdf: "Export PDF",
  exportUploadPdf: "Export & Upload PDF",
  removeTable: "Remove Table",
  totalWattsLabel: "Total Watts:",
  adjustedWattsLabel: (margin) => `Adjusted Watts (${margin}% safety margin):`,
  apparentPower: "Potencia Aparente:",
  currentPerPhase: "Current per Phase:",
  current: "Current:",
  pduTypeLabel: "PDU Type:",
  positionLabel: "Position:",
  hoistNote: "Additional Hoist Power Required: CEE32A 3P+N+G",
  notAvailable: "N/A",
  savedSetLoaded: (count) =>
    `${count} saved table(s) loaded for this job. Edit them and re-export to update the saved set.`,
  pfInfoTitle: "Recommended power factor by fixture type",
  pfInfoFootnote:
    "You can adjust the PF per item if the manufacturer specifies a different value.",
  loadingOverrideData: "Loading tour override data...",
  toastSuccess: "Success",
  toastError: "Error",
  toastMissingNameTitle: "Missing table name",
  toastMissingNameBody: "Please enter a name for the table",
  toastNoJobTitle: "No job selected",
  toastNoJobBody: "Please select a job before exporting.",
  toastNoTourDataTitle: "No tour data",
  toastNoTourDataBody: "Tour data not loaded",
  toastPdfGenerated: "PDF has been generated and downloaded successfully.",
  toastPdfUploaded: "PDF has been generated and uploaded successfully.",
  toastPdfAutoCompleted: (count) =>
    `PDF uploaded successfully. ${count} Consumos task(s) auto-completed.`,
  toastPdfError: "Failed to generate or upload the PDF.",
  toastDefaultSaved: "Tour default saved successfully",
  toastDefaultSaveError: (message) => `Failed to save tour default: ${message}`,
  toastNoUnsavedDefaultsTitle: "No unsaved tables",
  toastNoUnsavedDefaultsBody:
    "All tables have already been saved as defaults",
  toastDefaultsSaved: (count) => `${count} default table(s) saved successfully`,
  toastDefaultsPartial: (saved, failedNames) =>
    `${saved} saved, ${failedNames.length} failed: ${failedNames.join(", ")}`,
  toastDefaultsFailed: (failedNames) =>
    `Failed to save default tables: ${failedNames.join(", ")}`,
  toastOverrideSaved: "Tour override saved successfully",
  toastOverrideSaveError: "Failed to save tour override",
  toastOverrideUpdated: "Override updated successfully",
  toastOverrideDeleted: "Override deleted successfully",
  toastOverrideDeleteError: "Failed to delete override",
  toastTableNotFound: "Power requirement table not found",
  controls: ENGLISH_POWER_TABLE_CONTROL_LABELS,
};

const SPANISH_LABELS: ConsumosLabels = {
  title: "Calculadora de Potencia",
  tourDefaultsBadge: "Modo Valores por Defecto",
  tourDefaultsNoticeTitle: "Modo Valores por Defecto de Gira Activo",
  tourDefaultsNoticeBody:
    "Las tablas que crees aquí se guardarán como valores por defecto para todas las fechas de la gira, salvo que se anulen específicamente.",
  creatingDefaultsFor: "Creando valores por defecto para:",
  overrideBadge: "Modo Anulación",
  overrideNoticeTitle: "Modo Anulación Activo",
  overrideNoticeBody:
    "Este trabajo es parte de una gira. Las tablas que crees se guardarán como anulaciones para la fecha específica de la gira.",
  existingDefaultsHeading: "Valores por Defecto de la Gira",
  readOnlyDefaultsHeading: "Valores por Defecto (Solo Lectura)",
  existingOverridesHeading: "Anulaciones Existentes",
  defaultBadge: "Por Defecto",
  savedBadge: "Guardado",
  overrideTableBadge: "Anulación",
  edit: "Editar",
  deleteAction: "Eliminar",
  fohSchuko:
    "Se requiere potencia de 16A en formato schuko hembra en posicion FoH",
  supply: "Suministro",
  supplyPlaceholder: "Seleccionar suministro",
  singlePhase: "Monofásico (230 V)",
  threePhase: "Trifásico (400 V LL)",
  voltage: "Voltaje",
  voltageHint: "230 V (1φ) o 400 V LL (3φ) por defecto en ES",
  powerFactor: "Factor de Potencia (PF)",
  powerFactorHint: "Usa 0.9 como referencia",
  safetyMargin: "Margen de Seguridad",
  safetyMarginPlaceholder: "Seleccionar Margen de Seguridad",
  selectJob: "Seleccionar Trabajo",
  selectJobPlaceholder: "Seleccione un trabajo",
  stage: "Stage",
  tableName: "Nombre de la Tabla",
  defaultName: "Nombre del Valor por Defecto",
  tableNamePlaceholder: "Ingrese el nombre de la tabla",
  defaultNamePlaceholder: "Ingrese el nombre del valor por defecto",
  editingTableSuffix: "(Editando Tabla)",
  editingOverrideSuffix: "(Editando Anulación)",
  position: "Posición",
  noPosition: "Sin posición",
  customOption: "Personalizada",
  customPosition: "Posición Personalizada",
  customPositionPlaceholder: "Ingrese una posición personalizada",
  colQuantity: "Cantidad",
  colLineName: "Nombre",
  lineNamePlaceholder: "Nombre de línea opcional",
  colComponent: "Componente",
  componentPlaceholder: "Seleccione componente",
  addComponent: "Agregar componente",
  customComponentTitle: "Nuevo componente",
  componentName: "Nombre",
  componentNamePlaceholder: "Ingrese el nombre del componente",
  componentWatts: "Vatios",
  componentType: "Tipo de fixture",
  saveComponent: "Agregar componente",
  cancel: "Cancelar",
  colWatts: "Vatios (por unidad)",
  colPf: "PF (tipo recomendado)",
  colTotalWatts: "Vatios Totales",
  deleteRowAria: "Eliminar fila",
  toastComponentSaved: "Componente añadido al catálogo",
  toastComponentSaveError: "Error al añadir el componente",
  addRow: "Agregar Fila",
  generateTable: "Generar Tabla",
  updateTable: "Actualizar Tabla",
  createOverride: "Crear Anulación",
  updateOverride: "Actualizar Anulación",
  reset: "Reiniciar",
  cancelEdit: "Cancelar Edición",
  saveDefaultTables: "Guardar Valores por Defecto",
  saveDefault: "Guardar",
  exportPdf: "Exportar PDF",
  exportUploadPdf: "Exportar y Subir PDF",
  removeTable: "Eliminar Tabla",
  totalWattsLabel: "Vatios Totales:",
  adjustedWattsLabel: (margin) =>
    `Vatios Ajustados (${margin}% margen de seguridad):`,
  apparentPower: "Potencia Aparente:",
  currentPerPhase: "Corriente por Fase:",
  current: "Corriente:",
  pduTypeLabel: "Tipo de PDU:",
  positionLabel: "Posición:",
  hoistNote: "Se requiere potencia adicional para motor: CEE32A 3P+N+G",
  notAvailable: "N/A",
  savedSetLoaded: (count) =>
    `Se cargaron ${count} tabla(s) guardadas para este trabajo. Edítalas y vuelve a exportar para actualizar el conjunto guardado.`,
  pfInfoTitle: "Power factor recomendado por tipo de fixture",
  pfInfoFootnote:
    "Puedes ajustar el PF por ítem si el fabricante especifica un valor distinto.",
  loadingOverrideData: "Cargando datos de anulación de gira...",
  toastSuccess: "Éxito",
  toastError: "Error",
  toastMissingNameTitle: "Falta el nombre de la tabla",
  toastMissingNameBody: "Por favor ingrese un nombre para la tabla",
  toastNoJobTitle: "No hay trabajo seleccionado",
  toastNoJobBody: "Por favor seleccione un trabajo antes de exportar.",
  toastNoTourDataTitle: "Sin datos de gira",
  toastNoTourDataBody: "Los datos de la gira no se han cargado",
  toastPdfGenerated: "El PDF se ha generado y descargado exitosamente.",
  toastPdfUploaded: "El PDF se ha generado y subido exitosamente.",
  toastPdfAutoCompleted: (count) =>
    `PDF subido exitosamente. ${count} tarea(s) de Consumos auto-completadas.`,
  toastPdfError: "Error al generar o subir el PDF.",
  toastDefaultSaved: "Valor por defecto de gira guardado",
  toastDefaultSaveError: (message) =>
    `Error al guardar valor por defecto: ${message}`,
  toastNoUnsavedDefaultsTitle: "Sin tablas nuevas",
  toastNoUnsavedDefaultsBody:
    "Todas las tablas ya están guardadas como valores por defecto",
  toastDefaultsSaved: (count) => `${count} valor(es) por defecto guardados`,
  toastDefaultsPartial: (saved, failedNames) =>
    `${saved} guardado(s), ${failedNames.length} fallido(s): ${failedNames.join(", ")}`,
  toastDefaultsFailed: (failedNames) =>
    `No se pudo guardar ningún valor por defecto: ${failedNames.join(", ")}`,
  toastOverrideSaved: "Anulación guardada para la fecha de gira",
  toastOverrideSaveError: "Error al guardar la anulación de potencia",
  toastOverrideUpdated: "Anulación actualizada exitosamente",
  toastOverrideDeleted: "Anulación eliminada exitosamente",
  toastOverrideDeleteError: "Error al eliminar la anulación",
  toastTableNotFound: "No se encontró la tabla de requerimientos de potencia",
  controls: SPANISH_POWER_TABLE_CONTROL_LABELS,
};

export const SOUND_CONSUMOS_CONFIG: ConsumosDepartmentConfig = {
  department: "sound",
  backPath: "/sound",
  components: soundComponentDatabase,
  defaultSafetyMargin: 20,
  defaultPowerFactor: 0.95,
  features: {
    fohSchuko: true,
    perRowPf: false,
    lineName: false,
    legacyTourDefaultsFallback: true,
  },
  pdfFileName: (title) => `Sound Power Report - ${title}.pdf`,
  defaultsPdfFileName: (tourName) => `${tourName} - Sound Power Defaults.pdf`,
  defaultsReportTitle: (tourName) => `${tourName} - Sound Power Defaults`,
  defaultsSetName: (tourName) => `${tourName} Sound Defaults`,
  defaultsSetDescription: "Sound department power defaults",
  labels: ENGLISH_LABELS,
};

export const VIDEO_CONSUMOS_CONFIG: ConsumosDepartmentConfig = {
  department: "video",
  backPath: "/video",
  components: videoComponentDatabase,
  defaultSafetyMargin: 20,
  defaultPowerFactor: 0.9,
  features: {
    fohSchuko: true,
    perRowPf: false,
    lineName: true,
    legacyTourDefaultsFallback: false,
  },
  pdfFileName: (title) => `Video Power Report - ${title}.pdf`,
  defaultsPdfFileName: (tourName) => `${tourName} - Video Power Defaults.pdf`,
  defaultsReportTitle: (tourName) => `${tourName} - Video Power Defaults`,
  defaultsSetName: (tourName) => `${tourName} Video Defaults`,
  defaultsSetDescription: "Video department power defaults",
  labels: ENGLISH_LABELS,
};

export const LIGHTS_CONSUMOS_CONFIG: ConsumosDepartmentConfig = {
  department: "lights",
  backPath: "/lights",
  components: lightComponentDatabase,
  defaultSafetyMargin: 0,
  features: {
    fohSchuko: false,
    perRowPf: true,
    lineName: false,
    legacyTourDefaultsFallback: false,
  },
  pdfFileName: (title) => `Informe de Potencia - ${title}.pdf`,
  defaultsPdfFileName: (tourName) =>
    `${tourName} - Valores por Defecto de Potencia.pdf`,
  defaultsReportTitle: (tourName) =>
    `${tourName} - Valores por Defecto de Potencia`,
  defaultsSetName: (tourName) => `${tourName} Lights Defaults`,
  defaultsSetDescription: "Lights department power defaults",
  labels: SPANISH_LABELS,
};
