import type { ActivityCatalogEntry } from './types';

export const activityCatalogDefaults: Record<string, ActivityCatalogEntry> = {
  'job.created': {
    code: 'job.created',
    label: 'Job created',
    default_visibility: 'house_plus_job',
    severity: 'success',
    toast_enabled: true,
    template: '{actor_name} created job {job_title}',
  },
  'job.updated': {
    code: 'job.updated',
    label: 'Job updated',
    default_visibility: 'job_participants',
    severity: 'info',
    toast_enabled: true,
    template: '{actor_name} updated job {job_title}',
  },
  'job.deleted': {
    code: 'job.deleted',
    label: 'Job deleted',
    default_visibility: 'management',
    severity: 'warn',
    toast_enabled: true,
    template: '{actor_name} deleted a job',
  },
  'job.calltime.updated': {
    code: 'job.calltime.updated',
    label: 'Call time updated',
    default_visibility: 'job_participants',
    severity: 'info',
    toast_enabled: true,
    template: 'Call time updated for {job_title}',
  },
  'document.uploaded': {
    code: 'document.uploaded',
    label: 'Document uploaded',
    default_visibility: 'job_participants',
    severity: 'success',
    toast_enabled: true,
    template: '{actor_name} uploaded {file_name}',
  },
  'document.deleted': {
    code: 'document.deleted',
    label: 'Document deleted',
    default_visibility: 'job_participants',
    severity: 'warn',
    toast_enabled: true,
    template: '{actor_name} deleted {file_name}',
  },
  'hoja.updated': {
    code: 'hoja.updated',
    label: 'Hoja de ruta updated',
    default_visibility: 'job_participants',
    severity: 'info',
    toast_enabled: true,
    template: '{actor_name} updated Hoja de ruta',
  },
  'flex.folders.created': {
    code: 'flex.folders.created',
    label: 'Flex folders created',
    default_visibility: 'job_participants',
    severity: 'success',
    toast_enabled: true,
    template: 'Flex folders created: {folder}',
  },
  'flex.crew.updated': {
    code: 'flex.crew.updated',
    label: 'Flex crew updated',
    default_visibility: 'job_participants',
    severity: 'info',
    toast_enabled: true,
    template: 'Crew synced to Flex',
  },
  'staffing.availability.sent': {
    code: 'staffing.availability.sent',
    label: 'Availability email sent',
    default_visibility: 'management',
    severity: 'info',
    toast_enabled: false,
    template: 'Sent availability email to {tech_name}',
  },
  'staffing.availability.confirmed': {
    code: 'staffing.availability.confirmed',
    label: 'Availability confirmed',
    default_visibility: 'management',
    severity: 'success',
    toast_enabled: true,
    template: '{tech_name} confirmed availability',
  },
  'staffing.availability.declined': {
    code: 'staffing.availability.declined',
    label: 'Availability declined',
    default_visibility: 'management',
    severity: 'warn',
    toast_enabled: true,
    template: '{tech_name} declined availability',
  },
  'staffing.offer.sent': {
    code: 'staffing.offer.sent',
    label: 'Offer email sent',
    default_visibility: 'management',
    severity: 'info',
    toast_enabled: false,
    template: 'Offer sent to {tech_name}',
  },
  'staffing.offer.confirmed': {
    code: 'staffing.offer.confirmed',
    label: 'Offer accepted',
    default_visibility: 'job_participants',
    severity: 'success',
    toast_enabled: true,
    template: '{tech_name} accepted offer',
  },
  'staffing.offer.declined': {
    code: 'staffing.offer.declined',
    label: 'Offer declined',
    default_visibility: 'management',
    severity: 'warn',
    toast_enabled: true,
    template: '{tech_name} declined offer',
  },
  'assignment.created': {
    code: 'assignment.created',
    label: 'Assignment created',
    default_visibility: 'job_participants',
    severity: 'success',
    toast_enabled: true,
    template: '{actor_name} assigned {tech_name}',
  },
  'assignment.updated': {
    code: 'assignment.updated',
    label: 'Assignment updated',
    default_visibility: 'job_participants',
    severity: 'info',
    toast_enabled: true,
    template: 'Assignment updated for {tech_name}',
  },
  'assignment.removed': {
    code: 'assignment.removed',
    label: 'Assignment removed',
    default_visibility: 'job_participants',
    severity: 'warn',
    toast_enabled: true,
    template: '{actor_name} removed {tech_name}',
  },
  'timesheet.submitted': {
    code: 'timesheet.submitted',
    label: 'Timesheet submitted',
    default_visibility: 'management',
    severity: 'info',
    toast_enabled: true,
    template: '{actor_name} submitted timesheet',
  },
  'timesheet.approved': {
    code: 'timesheet.approved',
    label: 'Timesheet approved',
    default_visibility: 'job_participants',
    severity: 'success',
    toast_enabled: true,
    template: 'Timesheet approved',
  },
  'timesheet.rejected': {
    code: 'timesheet.rejected',
    label: 'Timesheet rejected',
    default_visibility: 'management',
    severity: 'warn',
    toast_enabled: true,
    template: 'Timesheet rejected',
  },
  'announcement.posted': {
    code: 'announcement.posted',
    label: 'Announcement posted',
    default_visibility: 'job_participants',
    severity: 'info',
    toast_enabled: true,
    template: '{title}',
  },
  'calendar.exported': {
    code: 'calendar.exported',
    label: 'Calendar exported',
    default_visibility: 'management',
    severity: 'info',
    toast_enabled: false,
    template: 'Calendar export generated',
  },
  'availability.unavailable.created': {
    code: 'availability.unavailable.created',
    label: 'Marked unavailable',
    default_visibility: 'management',
    severity: 'info',
    toast_enabled: true,
    template: '{actor_name} marked unavailable',
  },
  'availability.unavailable.updated': {
    code: 'availability.unavailable.updated',
    label: 'Updated unavailable',
    default_visibility: 'management',
    severity: 'info',
    toast_enabled: false,
    template: '{actor_name} updated unavailability',
  },
  'availability.unavailable.deleted': {
    code: 'availability.unavailable.deleted',
    label: 'Removed unavailable',
    default_visibility: 'management',
    severity: 'warn',
    toast_enabled: true,
    template: '{actor_name} removed unavailability',
  },
};

export function getActivityMeta(code: string): ActivityCatalogEntry | undefined {
  return activityCatalogDefaults[code];
}
