-- Cleanup auto-created logistics events (load/unload) generated by the previous trigger
-- Criteria:
--  - transport_type = 'trailer'
--  - license_plate IS NULL
--  - event_time = '09:00' for load or '22:00' for unload
--  - event_date = DATE(jobs.start_time) for load, DATE(jobs.end_time) for unload

-- First delete dependent rows in logistics_event_departments
WITH auto_events AS (
  SELECT le.id
  FROM public.logistics_events le
  JOIN public.jobs j ON j.id = le.job_id
  WHERE le.transport_type = 'trailer'
    AND le.license_plate IS NULL
    AND (
      (le.event_type = 'load' AND le.event_time = '09:00' AND le.event_date = DATE(j.start_time)) OR
      (le.event_type = 'unload' AND le.event_time = '22:00' AND le.event_date = DATE(j.end_time))
    )
)
DELETE FROM public.logistics_event_departments led
USING auto_events ae
WHERE led.event_id = ae.id;

-- Then delete the main events
DELETE FROM public.logistics_events le
USING public.jobs j
WHERE le.job_id = j.id
  AND le.transport_type = 'trailer'
  AND le.license_plate IS NULL
  AND (
    (le.event_type = 'load' AND le.event_time = '09:00' AND le.event_date = DATE(j.start_time)) OR
    (le.event_type = 'unload' AND le.event_time = '22:00' AND le.event_date = DATE(j.end_time))
  );

